#!/bin/sh

### BEGIN INIT INFO
# Provides: zsunray-init
# Required-Start: $local_fs $network $syslog $all
# Required-Stop:
# Should-Start: gdm
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: SunRay services
### END INIT INFO

. /lib/lsb/init-functions

set -e

unset _JAVA_OPTIONS

DESC="SunRay services"
case "$1" in
  start)
    log_daemon_msg "Starting $DESC"

    gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory --type bool --set /desktop/gnome/lockdown/disable_user_switching true
    gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory --type bool --set /apps/gnome-power-manager/general/can_hibernate false
    gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory --type bool --set /apps/gnome-power-manager/general/can_suspend false
    gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory --type bool --set /apps/gnome-power-manager/general/can_shutdown false
    gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory --type bool --set /apps/gnome-power-manager/general/can_restart false
    gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory --type bool --set /apps/gnome_settings_daemon/plugins/keyboard false
    gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory --type string --set /apps/gnome-screensaver/mode blank-only

    mkdir -p /tmp/SUNWut/config/xconfig/
    touch /tmp/SUNWut/config/xconfig/config.lock
    touch /tmp/SUNWut/config/xconfig/Xservers
    touch /tmp/SUNWut/config/xconfig/Xconfig

    cp /etc/gdm/gdm.conf-sunray /etc/gdm/gdm.conf
    cp /etc/gdm/gdm.conf-sunray /etc/gdm/gdm-cdd.conf

    /etc/init.d/openbsd-inetd start
    /etc/init.d/gdm restart
    /etc/init.d/utacleanup start
    /etc/init.d/utds start
    /etc/init.d/utsyscfg start
    [ -x /etc/init.d/utstorage ] && /etc/init.d/utstorage start
    /etc/init.d/utsvc start

    log_progress_msg "$DESC"
    log_end_msg 0
    ;;
  stop)
    log_daemon_msg "Stopping $DESC"
    /etc/init.d/utsvc stop
    [ -x /etc/init.d/utstorage ] && /etc/init.d/utstorage stop
    /etc/init.d/utacleanup stop
    /etc/init.d/utds stop
    /etc/init.d/utsyscfg stop
    /usr/bin/pkill -9 Xnewt
    /usr/bin/pkill utaction

    log_progress_msg "$DESC"
    log_end_msg 0
    ;;
  restart|force-reload)
    $0 stop
    $0 start
    ;;
  *)
    N=/etc/init.d/zsunray-init
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
