#! /bin/sh
### BEGIN INIT INFO
# Provides:          zsunray-init
# Should-Stop:       $gdm
# Should-Start:      $gdm
# Required-Start:    $local_fs $openbsd-inetd $gdm
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sun Ray services
### END INIT INFO

. /lib/lsb/init-functions

set -e

unset _JAVA_OPTIONS

. /etc/profile.d/sunray.sh

DESC="Sun Ray services"
case "$1" in
  start)
    mount -o remount,dev /tmp

    log_daemon_msg "Starting $DESC"
    /etc/init.d/utsyscfg start
    utstart
    log_progress_msg "$DESC"
    log_end_msg 0
    ;;
  stop)
    log_daemon_msg "Stopping $DESC"
    utstop
    /etc/init.d/utsyscfg stop
    log_progress_msg "$DESC"
    log_end_msg 0
    ;;
  restart|force-reload)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
